const materiasCam = {
    eso1: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Biología y Geología",
        "Educación Plástica, Visual y Audiovisual",
        "Música",
        "Segunda Lengua Extranjera",
        "Ciencias de la Computación",
    ],
    eso2: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos y Éticos",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Tecnología y Digitalización",
        "Segunda Lengua Extranjera",
        "Ciencias de la Computación",
    ],
    eso3: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Biología y Geología",
        "Física y Química",
        "Música",
        "Tecnología y Digitalización",
        "Segunda Lengua Extranjera",
    ],
    eso4: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Biología y Geología",
        "Digitalización",
        "Economía y Emprendimiento",
        "Expresión Artística",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Latín",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología",
        "Filosofía"
    ],
    bach1: [
        "Educación Física",
        "Filosofía",
        "Lengua Castellana y Literatura I",
        "Lengua Extranjera I",
        "Dibujo Artístico I",
        "Cultura Audiovisual",
        "Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño I",
        "Proyectos Artísticos",
        "Volumen",
        "Análisis Musical I",
        "Artes Escénicas I",
        "Coro y Técnica Vocal I",
        "Lenguaje y Práctica Musical",
        "Matemáticas I",
        "Biología, Geología y Ciencias Ambientales",
        "Dibujo Técnico I",
        "Física y Química",
        "Tecnología e Ingeniería I",
        "Matemáticas Generales",
        "Economía, Emprendimiento y Actividad Empresarial",
        "Latín I",
        "Matemáticas Aplicadas a las Ciencias Sociales I",
        "Economía",
        "Griego I",
        "Historia del Mundo Contemporáneo",
        "Literatura Universal",
        "Segunda Lengua Extranjera",
        "",
        "",

    ], 
    bach2: [
        "Historia de España",
        "Historia de la Filosofía",
        "Lengua Castellana y Literatura II",
        "Lengua Extranjera II",
        "Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño II",
        "Diseño",
        "Fundamentos Artísticos",
        "Técnicas de Expresión Gráfico-plástica",
        "Análisis Musical II",
        "Artes Escénicas II",
        "Coro y Técnica Vocal II",
        "Historia de la Música y de la Danza",
        "Literatura Dramática",
        "Matemáticas II",
        "Matemáticas Aplicadas a las Ciencias Sociales II",
        "Biología",
        "Dibujo Técnico II",
        "Física",
        "Geología y Ciencias Ambientales",
        "Química",
        "Tecnología e Ingeniería II",
        "Ciencias Generales",
        "Movimientos Culturales y Artísticos",
        "Latín II",
        "Empresa y Diseño de Modelos de Negocio",
        "Geografía",
        "Griego II",
        "Historia del Arte",
        "Segunda Lengua Extranjera",
    ]
}