const materiasCataluna = {
    eso1: [
        "Aranès i Literatura a l'Aran",
        "Biologia i Geologia",
        "Ciències Socials Geografia i Història",
        "Cultura Clàssica",
        "Educació Física",
        "Educació Plàstica, Visual i Audiovisual",
        "Emprenedoria ",
        "Física i Química",
        "Llengua Castellana i Literatura",
        "Llengua Catalana i Literatura",
        "Llengua Estrangera",
        "Matemàtiques",
        "Música",
        "Robòtica i Programació",
        "Segona Llengua Estrangera",
        "Tecnologia i Digitalització",
    ],
    eso2: [
        "Aranès i Literatura a l'Aran",
        "Biologia i Geologia",
        "Ciències Socials Geografia i Història",
        "Cultura Clàssica",
        "Educació Física",
        "Educació Plàstica, Visual i Audiovisual",
        "Emprenedoria ",
        "Física i Química",
        "Llengua Castellana i Literatura",
        "Llengua Catalana i Literatura",
        "Llengua Estrangera",
        "Matemàtiques",
        "Música",
        "Robòtica i Programació",
        "Segona Llengua Estrangera",
        "Tecnologia i Digitalització",
    ],
    eso3: [
        "Aranès i Literatura a l'Aran",
        "Biologia i Geologia",
        "Ciències Socials Geografia i Història",
        "Cultura Clàssica",
        "Educació Física",
        "Educació Plàstica, Visual i Audiovisual",
        "Emprenedoria ",
        "Física i Química",
        "Llengua Castellana i Literatura",
        "Llengua Catalana i Literatura",
        "Llengua Estrangera",
        "Matemàtiques",
        "Música",
        "Robòtica i Programació",
        "Segona Llengua Estrangera",
        "Tecnologia i Digitalització",
    ],
    eso4: [
        "Aranès i Literatura a l'Aran",
        "Arts Escèniques i Dansa",
        "Biologia i Geologia",
        "Ciències Socials Geografia i Història",
        "Cultura Científica",
        "Cultura Clàssica",
        "Digitalització",
        "Economia Bàsica",
        "Educació en Valors Cívics i Ètics",
        "Educació Física",
        "Emprenedoria",
        "Expressió Artística",
        "Filosofia",
        "Física i Química",
        "Formació i Orientació Personal i Professional",
        "Llatí Llengua i Cultura",
        "Llengua Castellana i Literatura",
        "Llengua Catalana i Literatura",
        "Llengua Estrangera",
        "Matemàtiques",
        "Música",
        "Segona Llengua Estrangera",
        "Tecnologia",

    ],
    bach1: ['Anàlisi Musical', 'Arts Escèniques', 'Biologia', 'Biomedicina', 'Cor i Tècnica Vocal', 'Cultura Audiovisual', 'Dibuix Tècnic', 'Dibuix Tècnic Aplicat a les Arts Plàstiques i el Disseny', 'Economia', 'Economia, Emprenedoria i Activitat Empresarial', 'Educació Física', 'Filosofia', 'Formació i Orientació Personal i Professional', "Funcionament de l'Empresa", 'Física', 'Geologia i Ciències Ambientals', 'Història del Món Contemporani', 'Literatura Universal', 'Llengua Castellana i Literatura', 'Llengua Catalana i Literatura', 'Llengua Estrangera', 'Llengua i Cultura Gregues', 'Llengua i Cultura Llatines ', 'Llenguatge i Pràctica Musical', 'Matemàtiques', 'Matemàtiques Aplicades a les Ciències Socials', 'Matemàtiques Generals', 'Món Clàssic', 'Programació', 'Projectes Artístics', 'Psicologia', 'Química', 'Segona Llengua Estrangera', 'Tecnologia i Enginyeria', 'Volum'],
    bach2: ['Anàlisi Musical', 'Arts Escèniques', 'Biologia', 'Ciències Generals', 'Cor i Tècnica Vocal', 'Creació Fotogràfica i Cinema', 'Dibuix Tècnic', 'Dibuix Tècnic Aplicat a les Arts Plàstiques i el Disseny', 'Disseny', 'Fonaments Artístics', 'Formació i Orientació Personal i Professional', "Funcionament de l'Empresa i Disseny de Models de Negoci", 'Física', 'Geografia', 'Geologia i Ciències Ambientals', 'Història', "Història de l'Art", 'Història de la Filosofia', 'Història de la Música i de la Dansa', 'Literatura Castellana', 'Literatura Catalana', 'Literatura Dramàtica', 'Llengua Castellana i Literatura', 'Llengua Catalana i Literatura', 'Llengua Estrangera', 'Llengua i Cultura Gregues', 'Llengua i Cultura Llatines', 'Llenguatges Artístics Contemporanis', 'Matemàtiques ', 'Matemàtiques Aplicades a les Ciències Socials', 'Moviments Culturals i Artístics', "Projecte de Comissariat d'Exposicions", 'Química', 'Segona Llengua Estrangera', 'Tecnologia i Enginyeria', "Tècniques d'Expressió Graficoplàstica"]
}