const materiasRioja = {
    ei: [
        'Todas las áreas',
    ],
    ep1: [
        "Lengua Vasca y Literatura",
        "Lengua Castellana y Literatura",
        "Primera Lengua extranjera",
        "Matemáticas",
        "Conocimiento del medio natural, social y cultural",
        "Educación Artística",
        "Educación Física",
    ],
    ep2: [
        "Lengua Vasca y Literatura",
        "Lengua Castellana y Literatura",
        "Primera Lengua extranjera",
        "Matemáticas",
        "Conocimiento del medio natural, social y cultural",
        "Educación Artística",
        "Educación Física",
    ],
    ep3: [
        "Lengua Vasca y Literatura",
        "Lengua Castellana y Literatura",
        "Primera Lengua extranjera",
        "Matemáticas",
        "Conocimiento del medio natural, social y cultural",
        "Educación Artística",
        "Educación Física",
    ],
    ep4: [
        "Lengua Vasca y Literatura",
        "Lengua Castellana y Literatura",
        "Primera Lengua extranjera",
        "Matemáticas",
        "Conocimiento del medio natural, social y cultural",
        "Educación Artística",
        "Educación Física",
    ],
    ep5: [
        "Lengua Vasca y Literatura",
        "Lengua Castellana y Literatura",
        "Primera Lengua extranjera",
        "Matemáticas",
        "Conocimiento del medio natural, social y cultural",
        "Educación Artística",
        "Educación Física",
    ],
    ep6: [
        "Lengua Vasca y Literatura",
        "Lengua Castellana y Literatura",
        "Primera Lengua extranjera",
        "Matemáticas",
        "Conocimiento del medio natural, social y cultural",
        "Educación Artística",
        "Educación Física",
        "Valores cívicos y éticos",
    ],
    eso1: [
        "Bienestar físico y emocional",
        "Ciencias de la Naturaleza",
        "Educación en valores cívicos y éticos",
        "Educación Física",
        "Educación plástica, visual y audiovisual",
        "Geografía e Historia",
        "Iniciación a la tecnología y la digitalización",
        "Lengua Castellana y Literatura",
        "Lengua Vasca y Literatura",
        "Primera Lengua extranjera",
        "Matemáticas",
        "Música",
        "Segunda lengua extranjera",
    ],
    eso2: [
        "Bienestar físico y emocional",
        "Ciencias de la Naturaleza",
        "Educación Física",
        "Educación plástica, visual y audiovisual",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Vasca y Literatura",
        "Primera Lengua extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Segunda lengua extranjera",
    ],
    eso3: [
        "Bienestar físico y emocional",
        "Biología, Geología",
        "Cultura científica",
        "Cultura clásica",
        "Educación Física",
        "Educación plástica, visual y audiovisual",
        "Expresión artística",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Vasca y Literatura",
        "Matemáticas",
        "Música",
        "Primera Lengua extranjera",
        "Segunda lengua extranjera",
        "Tecnología y Digitalización",
    ],
    eso4: [
        "Artes Escénicas",
        "Biología y Geología",
        "Ciencias Aplicadas a la actividad profesional",
        "Cultura Científica",
        "Digitalización",
        "Economía y Emprendimiento",
        "Educación Física",
        "Expresión Artística",
        "Filosofía aplicada al desarrollo personal y social",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Geografía e Historia",
        "Latín",
        "Lengua Castellana y Literatura",
        "Lengua Vasca y Literatura",
        "Matemáticas A",
        "Matemáticas B",
        "Música",
        "Primera Lengua Extranjera",
        "Tecnología",
        "Segunda Lengua Extranjera",
    ],
    bach1: [
        'Análisis Musical', 
        'Artes Escénicas', 
        'Biología, Geología y Ciencias Ambientales', 
        'Coro y Técnica Vocal', 
        'Cultura Audiovisual', 
        'Dibujo Artístico', 
        'Dibujo Técnico', 
        'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 
        'Economía', 
        'Economía, Emprendimiento y Actividad Empresarial', 
        'Educación Física', 
        'Filosofía', 
        'Física y Química', 
        'Griego', 
        'Historia del Mundo Contemporáneo', 
        'Latín', 
        'Lengua Castellana y Literatura', 
        'Lengua Vasca y Literatura', 
        'Lenguaje y Práctica Musical', 
        'Literatura Universal', 
        'Matemáticas', 
        'Matemáticas Aplicadas a las Ciencias Sociales', 
        'Matemáticas Generales', 
        'Primera Lengua Extranjera', 
        'Proyectos Artísticos', 
        'Segunda Lengua Extranjera', 
        'Tecnología e Ingeniería', 
        'Volumen'
    ],
    bach2: [
        'Análisis Musical', 
        'Artes Escénicas', 
        'Biología', 
        'Ciencias Generales', 
        'Coro y Técnica Vocal', 
        'Dibujo Artístico', 
        'Dibujo Técnico', 
        'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 
        'Diseño', 
        'Empresa y Diseño de Modelos de Negocio', 
        'Fundamentos Artísticos', 
        'Física', 
        'Geografía', 
        'Geología y Ciencias Ambientales', 
        'Griego', 
        'Historia de España', 
        'Historia de la Filosofía', 
        'Historia de la Música y de la Danza', 
        'Historia del Arte', 
        'Latín', 
        'Lengua Castellana y Literatura', 
        'Lengua Vasca y Literatura', 
        'Literatura Dramática', 
        'Matemáticas', 
        'Matemáticas Aplicadas a las Ciencias Sociales', 
        'Movimientos Culturales y Artísticos', 
        'Primera Lengua Extranjera', 
        'Química', 
        'Segunda Lengua Extranjera', 
        'Técnicas de Expresión Gráfico-plástica'],
        'Tecnología e Ingeniería', 
}