const materiasCyL = {
    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Tecnología y Digitalización",
        "Segunda Lengua Extranjera",
    ],
    eso2: [
        "Cultura Clásica",
        "Educación Física",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Segunda Lengua Extranjera",
    ],
    eso3: [
        "Biología y Geología",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Educación Plástica, Visual y Audiovisual",
        "Tecnología y Digitalización",
        "Control y Robótica",
        "Iniciación a la Actividad Emprendedora y Empresarial",
        "Segunda Lengua Extranjera",
        "Taller de Artes Plásticas",
        "Taller de Expresión Musical",
    ],
    eso4: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Biología y Geología",
        "Economía y Emprendimiento",
        "Física y Química",
        "Latín",
        "Digitalización",
        "Expresión Artística",
        "Formación y Orientación Personal y Profesional",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología",
        "Cultura Científica",
        "Cultura Clásica",
        "Educación Financiera",
        "Formación para la Empresa y el Empleo",
        "Geografía Económica",
        "Laboratorio de Ciencias",
        "Lengua y Cultura Gallega",
        "Literatura Universal",
        "Programación Informática",
        "Taller de Artes Escénicas",
        "Taller de Filosofía",
    ],
    bach1: [
        'Anatomía Aplicada',
        'Análisis Musical',
        'Artes Escénicas',
        'Biología, Geología y Ciencias Ambientales',
        'Coro y Técnica Vocal',
        'Cultura Audiovisual',
        'Cultura Científica',
        'Dibujo Técnico',
        'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño',
        'Economía',
        'Economía, Emprendimiento y Actividad Empresarial',
        'Educación Física',
        'Filosofía',
        'Física y Química',
        'Griego',
        'Historia del Mundo Contemporáneo',
        'Latín',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Lenguaje y Práctica Musical',
        'Literatura Universal',
        'Matemáticas Aplicadas a las Ciencias Sociales',
        'Matemáticas Generales',
        'Proyectos Artísticos',
        'Segunda Lengua Extranjera',
        'Tecnología e Ingeniería',
        'Tecnologías de la Información y la Comunicación',
        'Volumen',
    ],
    bach2: [
        'Artes Escénicas',
        'Biología',
        'Ciencias Generales',
        'Coro y Técnica Vocal',
        'Dibujo Técnico',
        'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño',
        'Diseño',
        'Empresa y Diseño de Modelos de Negocio',
        'Fundamentos Artísticos',
        'Física',
        'Geografía',
        'Geología y Ciencias Ambientales',
        'Griego',
        'Historia de España',
        'Historia de la Filosofía',
        'Historia de la Música y de la Danza',
        'Historia del Arte',
        'Latín',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Literatura Dramática',
        'Matemáticas Aplicadas a las Ciencias Sociales',
        'Movimientos Culturales y Artísticos',
        'Psicología',
        'Química',
        'Segunda Lengua Extranjera',
        'Tecnología e Ingeniería',
        'Tecnologías de la Información y la Comunicación',
        'Técnicas de Expresión Gráfico-plástica'
    ],
}