const materiasCyL = {
    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Tecnología y Digitalización",
        "Segunda Lengua Extranjera",
    ],
    eso2: [
        "Cultura Clásica",
        "Educación Física",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Segunda Lengua Extranjera",
    ],
    eso3: [
        "Biología y Geología",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Educación Plástica, Visual y Audiovisual",
        "Tecnología y Digitalización",
        "Control y Robótica",
        "Iniciación a la Actividad Emprendedora y Empresarial",
        "Segunda Lengua Extranjera",
        "Taller de Artes Plásticas",
        "Taller de Expresión Musical",
    ],
    eso4: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Biología y Geología",
        "Economía y Emprendimiento",
        "Física y Química",
        "Latín",
        "Digitalización",
        "Expresión Artística",
        "Formación y Orientación Personal y Profesional",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología",
        "Cultura Científica",
        "Cultura Clásica",
        "Educación Financiera",
        "Formación para la Empresa y el Empleo",
        "Geografía Económica",
        "Laboratorio de Ciencias",
        "Lengua y Cultura Gallega",
        "Literatura Universal",
        "Programación Informática",
        "Taller de Artes Escénicas",
        "Taller de Filosofía",
    ],
    bach1: [

    ],
    bach2: [

    ],
}