const materiasCantabria = {
    ei: ['Todas las áreas'],
    ep1: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
    ep2: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
    ep3: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
    ep4: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
    ep5: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos y Éticos"
    ],
    ep6: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
}