const materiasAragon = {
    eso1: [
        "Aragonés",
        "Catalán",
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Música",
        "Lengua Extranjeranglés",
        "Segunda Lengua Extranjera Francés",
    ],
    eso2: [
        "Aragonés",
        "Catalán",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Lengua Extranjeranglés",
        "Segunda Lengua Extranjera Francés",
        "Tecnología y digitalización",
    ],
    eso3: [
        "Aragonés",
        "Catalán",
        "Biología y Geología",
        "Educación Física",
        "Educación en Valores Cívicos y Éticos",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Música",
        "Lengua Extranjeranglés",
        "Tecnología y digitalización",
        "Cultura Clásica",
        "Economía social",
        "Iniciación a la Filosofía",
        "Programación y Robótica",
        "Segunda Lengua Extranjera Francés",
    ],
    eso4: [
        "Aragonés",
        "Catalán",
        "Artes Escénicas y Danza",
        "Biología y Geología",
        "Cultura y Patrimonio de Aragón",
        "Cultura Científica",
        "Cultura Clásica",
        "Digitalización",
        "Economía y Emprendimiento",
        "Educación Física",
        "Expresión artística",
        "Filosofía",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Geografía e Historia",
        "Latín",
        "Lengua Castellana y Literatura",
        "Lengua Extranjeranglés",
        "Matemáticas A o Matemáticas B",
        "Matemáticas para la toma de decisiones",
        "Música",
        "Oratoria y Escritura",
        "Segunda Lengua extranjera Francés",
        "Tecnología",
    ],
    bach1: ['Anatomía Aplicada', 'Análisis Musical', 'Aragonés', 'Artes Escénicas', 'Biología, Geología y Ciencias Ambientales', 'Catalán', 'Coro y Técnica Vocal', 'Cultura Audiovisual', 'Cultura y Patrimonio de Aragón', 'Dibujo Artístico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Dibujo Técnico', 'Economía, Emprendimiento y Actividad Empresarial', 'Economía', 'Educación Física', 'Educación para la Ciudadanía y los Derechos Humanos', 'Filosofía', 'Física y Química', 'Griego', 'Historia del mundo contemporáneo', 'Informática', 'Latín', 'Lengua Castellana y Literatura', 'Lengua Extranjera Inglés', 'Lenguaje y Práctica Musical', 'Literatura universal', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Matemáticas Generales', 'Matemáticas', 'Oratoria', 'Proyectos Artísticos', 'Segunda Lengua Extranjera', 'Tecnología engeniería', 'Volumen'],

    bach2: ['Análisis Musical', 'Aragonés', 'Artes Escénicas', 'Biología', 'Catalán', 'Ciencias Generales', 'Ciencias de la Tierra y del Medio Ambiente', 'Coro y Técnica Vocal', 'Cultura y Patrimonio de Aragón', 'Dibujo Artístico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Dibujo Técnico', 'Diseño', 'Educación Física y Vida Activa', 'Empresa y Diseño de Modelos de Negocio', 'Fundamentos Artísticos', 'Fundamentos de Administración y Gestión', 'Física', 'Geografía', 'Geología y Ciencias Ambientales', 'Griego', 'Historia de España', 'Historia de la Filosofía', 'Historia de la Música y de la Danza', 'Historia del Arte', 'Imagen y Sonido', 'Informática', 'Latín', 'Lengua Castellana y Literatura', 'Lengua Extranjera Inglés', 'Literatura Dramática', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Matemáticas', 'Movimientos Culturales y Artísticos', 'Oratoria', 'Proyecto de Investigación en Inovaciónntegrado', 'Psicología', 'Química', 'Segunda Lengua Extranjera', 'Tecnología engeniería', 'Técnicas de Expresión Gráfico-plástica', 'Unión Europea'],
}