const materiasAragon = {
    eso1: [
        "Aragonés",
        "Catalán",
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Música",
        "Lengua Extranjera Inglés",
        "Segunda Lengua Extranjera Francés",
    ],
    eso2: [
        "Aragonés",
        "Catalán",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Lengua Extranjera Inglés",
        "Segunda Lengua Extranjera Francés",
        "Tecnología y digitalización",
    ],
    eso3: [
        "Aragonés",
        "Catalán",
        "Biología y Geología",
        "Educación Física",
        "Educación en Valores Cívicos y Éticos",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Música",
        "Lengua Extranjera Inglés",
        "Tecnología y digitalización",
        "Cultura Clásica",
        "Economía social",
        "Iniciación a la Filosofía",
        "Programación y Robótica",
        "Segunda Lengua Extranjera Francés",
    ],
    eso4: [
        "Aragonés",
        "Catalán",
        "Artes Escénicas y Danza",
        "Biología y Geología",
        "Cultura y Patrimonio de Aragón",
        "Cultura Científica",
        "Cultura Clásica II",
        "Digitalización",
        "Economía y Emprendimiento",
        "Educación Física",
        "Expresión artística",
        "Filosofía",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Geografía e Historia",
        "Latín",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera Inglés",
        "Matemáticas A o Matemáticas B",
        "Matemáticas para la toma de decisiones",
        "Música",
        "Oratoria y Escritura",
        "Segunda Lengua extranjera Francés",
        "Tecnología",
    ],
    bach1: [

    ],
    bach2: [

    ],
}