const materiasCanarias = {
    ei: ['Todas las áreas'],
    ep1: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
    ep2: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
    ep3: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos y Éticos",
    ],
    ep4: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos y Éticos",
    ],
    ep5: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Segunda Lengua Extranjera",
    ],
    ep6: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Segunda Lengua Extranjera",
    ],
    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Música",
        "Lengua Extranjera",
        "Tecnología y Digitalización",
        "Educación en Valores Cívico y Éticos"
    ],
    eso2: [
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Música",
        "Lengua Extranjera",
        "Tecnología y Digitalización"
    ],
    eso3: [
        "Biología y Geología",
        "Cultura Clásica",
        "Cultura y Ciudadanía Digital",
        "Economía Personal y Social",
        "Educación Física ",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Historia y Geografía de Canarias",
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Música",
        "Lengua Extranjera",
        "Tecnología y Digitalización",
        "Tecnología y Digitalización"
    ],
    eso4: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas A o Matemáticas B",
        "Biología y Geología",
        "Digitalización",
        "Economía y Emprendimiento",
        "Expresión Artística",
        "Filosofía ",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Latín",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología"
    ],
    bach1: [
        "Análisis Musical",
        "Artes Escénicas",
        "Educación Física",
        "Filosofía",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Dibujo Artístico",
        "Cultura Audiovisual",
        "Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño",
        "Proyectos Artísticos",
        "Volumen",
        "Coro y Técnica Vocal",
        "Cultura Audiovisual",
        "Lenguaje y Práctica Musical",
        "Matemáticas",
        "Biología, Geología y Ciencias Ambientales",
        "Dibujo Técnico",
        "Física y Química",
        "Tecnología e Ingeniería",
        "Matemáticas Generales",
        "Economía, Emprendimiento y Actividad Empresarial",
        "Latín",
        "Matemáticas Aplicadas a las Ciencias Sociales",
        "Economía",
        "Griego",
        "Historia del Mundo Contemporáneo",
        "Literatura Universal",
        "Anatomía Aplicada",
        "Cultura Científica",
        "Fotografía",
        "Historia de Canarias",
        "Iniciación a la Astronomía",
        "Informática y Digitalización",
        "Medio Natural Canario",
        "Taller de Etimología Grecolatina",
        "Talleres Artísticos",
        "Técnicas de Laboratorio"

    ],
    bach2: [
        "Dibujo Artístico",
        "Historia de España",
        "Historia de la Filosofía",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño",
        "Diseño",
        "Fundamentos Artísticos",
        "Técnicas de Expresión Gráfico-Plástica",
        "Análisis Musical",
        "Artes Escénicas",
        "Coro y Técnica Vocal",
        "Historia de la Música y de la Danza",
        "Literatura Dramática       ",
        "Matemáticas Aplicadas a las Ciencias Sociales",
        "Matemáticas",
        "Biología",
        "Dibujo Técnico",
        "Física",
        "Geología y Ciencias Ambientales",
        "Química",
        "Tecnología e Ingeniería",
        "Ciencias Generales",
        "Movimientos Culturales y Artísticos",
        "Latín",
        "Matemáticas Aplicadas a las Ciencias Sociales",
        "Empresa y Diseño de Modelos de Negocio",
        "Geografía",
        "Griego",
        "Historia del Arte",
        "Biología Humana",
        "Informática y Digitalización",
        "Acondicionamiento Físico",
        "Antropología y Sociología",
        "Bioestadística",
        "Electrotecnia",
        "Fundamentos de Administración y Gestión",
        "Imagen y Sonido",
        "La Mitología y las Artes",
        "Literatura Canaria",
        "Música y Sociedad",
        "Psicología",
        "Taller de Artes Integradas"
    ]
}