const materiasCanarias = {
    ei: [
        'Todas las áreas'
    ],
    ep1: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
    ep2: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
    ],
    ep3: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos y Éticos",
    ],
    ep4: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos y Éticos",
    ],
    ep5: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Segunda Lengua Extranjera",
    ],
    ep6: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Segunda Lengua Extranjera",
    ],
    eso1: [
        'Biología y Geología',
        'Educación Física',
        'Educación Plástica, Visual y Audiovisual',
        'Educación en Valores Cívico y Éticos',
        'Geografía e Historia',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Música',
        'Tecnología y Digitalización'
    ],
    eso2: [
        'Educación Física',
        'Educación Plástica, Visual y Audiovisual',
        'Física y Química',
        'Geografía e Historia',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Música',
        'Tecnología y Digitalización'
    ],
    eso3: [
        'Biología y Geología',
        'Cultura Clásica',
        'Cultura y Ciudadanía Digital',
        'Economía Personal y Social',
        'Educación Física ',
        'Educación Plástica, Visual y Audiovisual',
        'Física y Química',
        'Geografía e Historia',
        'Historia y Geografía de Canarias',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Música',
        'Tecnología y Digitalización'
    ],
    eso4: [
        'Biología y Geología',
        'Digitalización',
        'Economía y Emprendimiento',
        'Educación Física',
        'Expresión Artística',
        'Filosofía ',
        'Formación y Orientación Personal y Profesional',
        'Física y Química',
        'Geografía e Historia',
        'Latín',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas A o Matemáticas B',
        'Música',
        'Segunda Lengua Extranjera',
        'Tecnología'
    ],
    bach1: [
        'Anatomía Aplicada',
        'Análisis Musical',
        'Artes Escénicas',
        'Biología, Geología y Ciencias Ambientales',
        'Coro y Técnica Vocal',
        'Cultura Audiovisual',
        'Cultura Científica',
        'Dibujo Artístico',
        'Dibujo Técnico',
        'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño',
        'Economía',
        'Economía, Emprendimiento y Actividad Empresarial',
        'Educación Física',
        'Filosofía',
        'Fotografía',
        'Física y Química',
        'Griego',
        'Historia de Canarias',
        'Historia del Mundo Contemporáneo',
        'Informática y Digitalización',
        'Iniciación a la Astronomía',
        'Latín',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Lenguaje y Práctica Musical',
        'Literatura Universal',
        'Matemáticas',
        'Matemáticas Aplicadas a las Ciencias Sociales',
        'Matemáticas Generales',
        'Medio Natural Canario',
        'Proyectos Artísticos',
        'Taller de Etimología Grecolatina',
        'Talleres Artísticos',
        'Tecnología e Ingeniería',
        'Técnicas de Laboratorio',
        'Volumen'
    ],
    bach2: [
        'Acondicionamiento Físico',
        'Antropología y Sociología',
        'Análisis Musical',
        'Artes Escénicas',
        'Bioestadística',
        'Biología',
        'Biología Humana',
        'Ciencias Generales',
        'Coro y Técnica Vocal',
        'Dibujo Artístico',
        'Dibujo Técnico',
        'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño',
        'Diseño',
        'Electrotecnia',
        'Empresa y Diseño de Modelos de Negocio',
        'Fundamentos Artísticos',
        'Fundamentos de Administración y Gestión',
        'Física',
        'Geografía',
        'Geología y Ciencias Ambientales',
        'Griego',
        'Historia de España',
        'Historia de la Filosofía',
        'Historia de la Música y de la Danza',
        'Historia del Arte',
        'Imagen y Sonido',
        'Informática y Digitalización',
        'La Mitología y las Artes',
        'Latín',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Literatura Canaria',
        'Literatura Dramática       ',
        'Matemáticas',
        'Matemáticas Aplicadas a las Ciencias Sociales',
        'Movimientos Culturales y Artísticos',
        'Música y Sociedad',
        'Psicología',
        'Química',
        'Taller de Artes Integradas',
        'Tecnología e Ingeniería',
        'Técnicas de Expresión Gráfico-Plástica'
    ]
}