const materiasCanarias = {
    ei: ['Todas las áreas'],
    ep1: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación Emocional y para la Creatividad",
    ],
    ep2: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación Emocional y para la Creatividad",
    ],
    ep3: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos y Éticos",
        "Educación Emocional y para la Creatividad",
    ],
    ep4: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos y Éticos",
        "Educación Emocional y para la Creatividad",
    ],
    ep5: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación Emocional y para la Creatividad",
        " Segunda Lengua Extranjera",
    ],
    ep6: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Educación Emocional y para la Creatividad",
        " Segunda Lengua Extranjera",
    ],
}