const materiaNavarra = {
    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación en Valores Cívicos y Éticos",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Vasca Modelo A",
        "Lengua Vasca Modelo D",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Cultura Clásica",
    ],
    eso2: [
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Vasca Modelo A",
        "Lengua Vasca Modelo D",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Cultura Clásica",
    ],
    eso3: [
        "Biología y Geología",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Vasca Modelo A",
        "Lengua Vasca Modelo D",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Cultura Clásica",
    ],
    eso4: [
        "Biología y Geología",
        "Digitalización",
        "Economía y Emprendimiento",
        "Educación Física",
        "Expresión Artística",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Geografía e Historia",
        "Latín",
        "Lengua Castellana y Literatura",
        "Lengua Vasca Modelo A",
        "Lengua Vasca Modelo D",
        "Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Música",
        "Tecnología",
    ],
    bach1: ['Artes Escénicas', 'Biología, Geología y Ciencias Ambientales', 'Coro y Técnica Vocal', 'Cultura Audiovisual', 'Cultura Audiovisual', 'Dibujo Técnico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Economía, Emprendimiento y Actividad Empresarial', 'Economía', 'Educación Física', 'Filosofía', 'Física y Química', 'Griego', 'Historia del Mundo Contemporáneo', 'Latín', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Vasca ModeloA', 'Lengua Vasca ModeloD', 'Lenguaje y Práctica Musical', 'Literatura Universal', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Matemáticas Generales ', 'Proyectos Artísticos', 'Tecnología e Ingeniería I', 'Volumen'],
    bach2: ['Análisis Musical', 'Análisis Musical', 'Artes Escénicas', 'Biología', 'Ciencias Generales', 'Coro y Técnica Vocal', 'Dibujo Técnico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Diseño', 'Empresa y Diseño de Modelos de Negocio', 'Fundamentos Artísticos', 'Física', 'Geografía', 'Geología y Ciencias Ambientales', 'Griego', 'Historia de España', 'Historia de la Filosofía', 'Historia de la Música y de la Danza', 'Historia del Arte', 'Latín', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Vasca ModeloA', 'Lengua Vasca ModeloD', 'Literatura Dramática', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Movimientos Culturales y Artísticos', 'Química', 'Tecnología e Ingeniería II', 'Técnicas de Expresión Gráfico-plástica  ']
}