const materiaNavarra = {
    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación en Valores Cívicos y Éticos",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Vasca Modelo A",
        "Lengua Vasca Modelo D",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Cultura Clásica",
    ],
    eso2: [
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Vasca Modelo A",
        "Lengua Vasca Modelo D",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Cultura Clásica",
    ],
    eso3: [
        "Biología y Geología",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Vasca Modelo A",
        "Lengua Vasca Modelo D",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Cultura Clásica",
    ],
    eso4: [
        "Biología y Geología",
        "Digitalización",
        "Economía y Emprendimiento",
        "Educación Física",
        "Expresión Artística",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Geografía e Historia",
        "Latín",
        "Lengua Castellana y Literatura",
        "Lengua Vasca Modelo A",
        "Lengua Vasca Modelo D",
        "Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Música",
        "Tecnología",
    ],
    bach1: [
        "Educación Física.",
        "Filosofía.",
        "Lengua Castellana y Literatura",
        "Lengua Vasca ModeloA",
        "Lengua Vasca ModeloD",
        "Lengua Extranjera",
        "Cultura Audiovisual.",
        "Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño",
        "Proyectos Artísticos.",
        "Volumen.",
        "Artes Escénicas",
        "Coro y Técnica Vocal",
        "Cultura Audiovisual.",
        "Lenguaje y Práctica Musical",
        "Biología, Geología y Ciencias Ambientales.",
        "Dibujo Técnico",
        "Física y Química.",
        "Tecnología e Ingeniería I",
        "Matemáticas Generales ",
        "Economía, Emprendimiento y Actividad Empresarial.",
        "Economía.",
        "Griego",
        "Historia del Mundo Contemporáneo.",
        "Latín",
        "Literatura Universal.",
        "Matemáticas Aplicadas a las Ciencias Sociales"
    ],
    bach2: [
        "Historia de España.",
        "Historia de la Filosofía.",
        "Lengua Castellana y Literatura",
        "Lengua Vasca ModeloA",
        "Lengua Vasca ModeloD",
        "Lengua Extranjera",
        "Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño",
        "Diseño.",
        "Fundamentos Artísticos.",
        "Técnicas de Expresión Gráfico-plástica.  ",
        "Análisis Musical",
        "Análisis Musical",
        "Artes Escénicas",
        "Coro y Técnica Vocal",
        "Historia de la Música y de la Danza.",
        "Literatura Dramática.",
        "Biología.",
        "Dibujo Técnico",
        "Física.",
        "Geología y Ciencias Ambientales.",
        "Química.",
        "Tecnología e Ingeniería II",
        "Ciencias Generales",
        "Movimientos Culturales y Artísticos.",
        "Empresa y Diseño de Modelos de Negocio.",
        "Geografía.",
        "Griego",
        "Historia del Arte.",
        "Latín",
        "Matemáticas Aplicadas a las Ciencias Sociales"
    ]
}