const materiasRioja = {
    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Segunda Lengua Extranjera",
        "Suena la música",
        "Tecnología y Digitalización",
        "Tecnología para la vida",
    ],
    eso2: [
        "Educación ambiental",
        "Educación en valores cívicos y éticos",
        "Educación Física",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Segunda Lengua Extranjera",
    ],
    eso3: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Segunda Lengua Extranjera",
        "Cultura Clásica",
    ],
    eso4: [
        "Biología y geología",
        "Cultura científica",
        "Digitalización",
        "Economía y emprendimiento",
        "Educación Física",
        "Ética y filosofía",
        "Expresión artística",
        "Física y química",
        "Formación y orientación personal y profesional",
        "Geografía e Historia",
        "Latín",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología",
    ],
    bach1: [

    ],
    bach2: [

    ],
}