const materiasRioja = {
    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Segunda Lengua Extranjera",
        "Suena la música",
        "Tecnología y Digitalización",
        "Tecnología para la vida",
    ],
    eso2: [
        "Educación ambiental",
        "Educación en valores cívicos y éticos",
        "Educación Física",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Tecnología y Digitalización",
        "Segunda Lengua Extranjera",
    ],
    eso3: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Música",
        "Segunda Lengua Extranjera",
        "Cultura Clásica",
    ],
    eso4: [
        "Biología y geología",
        "Cultura científica",
        "Digitalización",
        "Economía y emprendimiento",
        "Educación Física",
        "Ética y filosofía",
        "Expresión artística",
        "Física y química",
        "Formación y orientación personal y profesional",
        "Geografía e Historia",
        "Latín",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología",
    ],
    bach1: [
        "Educación Física",
        "Filosofía",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Dibujo artístico",
        "Cultura audiovisual",
        "Dibujo técnico aplicado a las artes plásticas y al diseño",
        "Proyectos artísticos",
        "Volumen",
        "Análisis musical",
        "Artes escénicas",
        "Coro y técnica vocal ",
        "Lenguaje y práctica musical",
        "Biología, Geología y Ciencias ambientales",
        "Dibujo técnico",
        "Física y química",
        "Tecnología y ingeniería",
        "Matemáticas generales",
        "Economía, emprendimiento y actividad empresarial",
        "Economía",
        "Griego",
        "Historia del mundo contemporáneo",
        "Latín",
        "Literatura universal",
        "Matemáticas aplicadas a las ciencias sociales",
        "Segunda lengua extranjera Francés",
    ],
    bach2: [
        "Historia de España",
        "Historia de la Filosofía",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Dibujo técnico aplicado a las artes plásticas y al diseño",
        "Diseño",
        "Fundamentos artísticos",
        "Técnicas de expresión gráfico-plásticas",
        "Análisis musical",
        "Artes escénicas",
        "Coro y técnica vocal",
        "Historia de la música y la danza",
        "Literatura dramática",
        "Biología",
        "Dibujo técnico",
        "Física",
        "Geología y Ciencias ambientales",
        "Química",
        "Tecnología y ingeniería",
        "Ciencias generales",
        "Movimientos culturales y artísticos",
        "Empresa y diseño de modelos de negocio",
        "Geografía",
        "Griego",
        "Historia del arte",
        "Latín",
        "Matemáticas aplicadas a las ciencias sociales",
        "Segunda lengua extranjera Francés",
    ],
}