const materiasAsturias = {
    eso1: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Biología y Geología",
        "Educación Plástica, Visual y Audiovisual",
        "Música",
        "Segunda Lengua Extranjera",
        "Lengua Asturiana y Literatura",
        "Digitalización Aplicada",
    ],
    eso2: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Física y Química",
        "Música",
        "Tecnología y Digitalización",
        "Segunda Lengua Extranjera",
        "Lengua Asturiana y Literatura",
        "Cultura Clásica",
    ],
    eso3: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas",
        "Biología y Geología",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Tecnología y Digitalización",
        "Educación en Valores Cívicos y Éticos",
        "Segunda Lengua Extranjera",
        "Lengua Asturiana y Literatura",
        "Proyecto de Emprendimiento Social o Empresarial",
    ],
    eso4: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Biología y Geología",
        "Digitalización",
        "Economía y Emprendimiento",
        "Expresión Artística",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Latín",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología",
        "Filosofía",
        "Lengua Asturiana y Literatura",
    ],
    bach1: [

    ],
    bach2: [

    ],
}