const materiasCV = {
    eso1: ['Biología y Geología',
        'Biología y Geología',
        'Educación Física',
        'Educación Plástica, Visual y Audiovisual',
        'Física y Química',
        'Geografía e Historia',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Música',
        'Música',
        'Segunda Lengua Extranjera',
        'Tecnología y Digitalización',
        'Tecnología y Digitalización',
        'Valenciano: Lengua y Literatura',
        'Competencia Comunicativa Oral en Lengua Extranjera',
        'Laboratorio de Artes Escénicas',
        'Laboratorio de Creación Audiovisual',
        'Taller de Relaciones Digitales Responsables',
    ],
    eso2: ['Biología y Geología',
        'Educación Física',
        'Educación Plástica, Visual y Audiovisual',
        'Educación Plástica, Visual y Audiovisual',
        'Física y Química',
        'Física y Química',
        'Geografía e Historia',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Música',
        'Música',
        'Segunda Lengua Extranjera',
        'Tecnología y Digitalización',
        'Valenciano: Lengua y Literatura',
        'Emprendimiento Social y Sostenible',
        'Programación, Inteligencia Artificial y Robótica',
    ],
    eso3: ['Biología y Geología',
        'Biología y Geología',
        'Educación Física',
        'Educación Plástica, Visual y Audiovisual',
        'Educación Plástica, Visual y Audiovisual',
        'Física y Química',
        'Física y Química',
        'Geografía e Historia',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas',
        'Música',
        'Segunda Lengua Extranjera',
        'Tecnología y Digitalización',
        'Tecnología y Digitalización',
        'Valenciano: Lengua y Literatura',
        'Programación, Inteligencia Artificial y Robótica',
        'Creatividad Musical',
        'Cultura Clásica',
        'Programación, Inteligencia Artificial y Robótica',
        'Taller de Economía',
    ],
    eso4: ['Biología y Geología',
        'Digitalización',
        'Economía y Emprendimiento',
        'Educación Física',
        'Educación en Valores Cívicos y Éticos',
        'Expresión Artística',
        'Filosofía',
        'Formación y Orientación Personal y Profesional',
        'Física y Química',
        'Geografía e Historia',
        'Latín',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Matemáticas A o Matemáticas B',
        'Música',
        'Segunda Lengua Extranjera',
        'Segunda Lengua Extranjera',
        'Tecnología',
        'Valenciano: Lengua y Literatura',
        'Artes Escénicas',
        'Competencia Comunicativa Oral en Primera Lengua Extranjera',
        'Proyectos Interdisciplinarios',
        'Segunda Lengua Extranjera',
        'Taller de Profundización',
        'Taller de Refuerzo',
    ],
    bach1: [
        'Análisis Musical',
        'Artes Escénicas',
        'Biología Humana y Salud ',
        'Biología, Geología y Ciencias Ambientales',
        'Coro y Técnica Vocal',
        'Cultura Audiovisual',
        'Dibujo Artístico',
        'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño',
        'Dibujo Técnico',
        'Economía',
        'Economía, Emprendimiento y Actividad Empresarial',
        'Educación Física',
        'Filosofía',
        'Física y Química',
        'Griego',
        'Historia del Mundo Contemporáneo',
        'Latín',
        'Latín',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Lenguaje y Práctica Musical',
        'Literatura Universal',
        'Matemáticas Aplicadas a las Ciencias Sociales',
        'Matemáticas Generales ',
        'Matemáticas',
        'Programación, Redes y Sistemas Informáticos',
        'Proyectos Artísticos',
        'Segunda Lengua Extranjera',
        'Tecnología e Ingeniería',
        'Valenciano Lengua y Literatura',
        'Volumen',
        'Comunicación Audiovisual',
        'Cultura Jurídica y Democrática',
        'Descubriendo Nuestras Raíces Clásicas',
        'Geografía e Historia Valencianas',
        'Gestión de Proyectos de Emprendimiento',
        'Imagen y Sonido',
        'Psicología',
        'Producción Musical',
    ],

    bach2: [
        'Actividad Física para la Salud y el Desarrollo Personal',
        'Análisis Musical',
        'Artes Escénicas',
        'Biología',
        'Ciencias Generales',
        'Coro y Técnica Vocal',
        'Dibujo Artístico',
        'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño',
        'Dibujo Técnico',
        'Diseño',
        'El trabajo experimental en Física y Química',
        'Empresa y Diseño de Modelos de Negocio',
        'Fundamentos Artísticos',
        'Física',
        'Geografía',
        'Geología y Ciencias Ambientales',
        'Griego',
        'Historia de España',
        'Historia de la Filosofía',
        'Historia de la Música y de la Danza',
        'Historia del Arte',
        'Latín',
        'Lengua Castellana y Literatura',
        'Lengua Extranjera',
        'Literatura Dramática',
        'Matemáticas Aplicadas a las Ciencias Sociales',
        'Matemáticas',
        'Movimientos Culturales y Artísticos',
        'Programación, Redes y Sistemas Informáticos',
        'Química',
        'Segunda Lengua Extranjera',
        'Tecnología e Ingeniería',
        'Técnicas de Expresión Graficoplástica',
        'Valenciano Lengua y Literatura',
        'Comunicación Audiovisual',
        'Cultura Jurídica y Democrática',
        'Descubriendo Nuestras Raíces Clásicas',
        'Geografía e Historia Valencianas',
        'Gestión de Proyectos de Emprendimiento',
        'Imagen y Sonido, Psicología',
        'Producción Musical',
    ]
}

