const materiasCV = {
    bach1: [
        'Análisis Musical I',
         'Artes Escénicas I',
         'Biología Humana y Salud ',
         'Biología, Geología y Ciencias Ambientales',
         'Coro y Técnica Vocal I',
         'Cultura Audiovisual',
         'Dibujo Artístico I',
         'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño I',
         'Dibujo Técnico I',
         'Economía',
         'Economía, Emprendimiento y Actividad Empresarial',
         'Educación Física',
         'Filosofía',
         'Física y Química',
         'Griego I',
         'Historia del Mundo Contemporáneo',
         'Latín I',
         'Latín I',
         'Lengua Castellana y Literatura I',
         'Lengua Extranjera I',
         'Lenguaje y Práctica Musical',
         'Literatura Universal',
         'Matemáticas Aplicadas a las Ciencias Sociales I',
         'Matemáticas Aplicadas a las Ciencias Sociales I',
         'Matemáticas Generales ',
         'Matemáticas I',
         'Programación, Redes y Sistemas Informáticos I',
         'Proyectos Artísticos',
         'Segunda Lengua Extranjera I',
         'Tecnología e Ingeniería I',
         'Valenciano Lengua y Literatura I',
         'Volumen'
    ],

    bach2: [
        'Actividad Física para la Salud y el Desarrollo Personal',
         'Análisis Musical II',
         'Artes Escénicas II',
         'Biología',
         'Ciencias Generales',
         'Coro y Técnica Vocal II',
         'Dibujo Artístico II',
         'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño II',
         'Dibujo Técnico II',
         'Diseño',
         'El trabajo experimental en Física y Química',
         'Empresa y Diseño de Modelos de Negocio',
         'Fundamentos Artísticos',
         'Física',
         'Geografía',
         'Geología y Ciencias Ambientales',
         'Griego II',
         'Historia de España',
         'Historia de la Filosofía',
         'Historia de la Música y de la Danza',
         'Historia del Arte',
         'Latín II',
         'Lengua Castellana y Literatura II',
         'Lengua Extranjera II',
         'Literatura Dramática',
         'Matemáticas Aplicadas a las Ciencias Sociales II',
         'Matemáticas II',
         'Movimientos Culturales y Artísticos',
         'Programación, Redes y Sistemas Informáticos II',
         'Química',
         'Segunda Lengua Extranjera II',
         'Tecnología e Ingeniería II',
         'Técnicas de Expresión Graficoplástica',
         'Valenciano Lengua y Literatura II'
    ]
}

