const materiasGalicia = {
    ei: [
        'Todas las áreas'
    ],
    ep1: [
        "Ciencias de la Naturaleza",
        "Ciencias Sociales",
        "Educación Física",
        "Educación Plástica y Visual",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Música y Danza",
    ],
    ep2: [
        "Ciencias de la Naturaleza",
        "Ciencias Sociales",
        "Educación Física",
        "Educación Plástica y Visual",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Música y Danza",
    ],
    ep3: [
        "Ciencias de la Naturaleza",
        "Ciencias Sociales",
        "Educación Física",
        "Educación Plástica y Visual",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Música y Danza",
    ],
    ep4: [
        "Ciencias de la Naturaleza",
        "Ciencias Sociales",
        "Educación Física",
        "Educación Plástica y Visual",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Música y Danza",
    ],
    ep5: [
        "Ciencias de la Naturaleza",
        "Ciencias Sociales",
        "Educación Física",
        "Educación Plástica y Visual",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Música y Danza",
    ],
    ep6: [
        "Ciencias de la Naturaleza",
        "Ciencias Sociales",
        "Educación Física",
        "Educación Plástica y Visual",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Música y Danza",
        "Educación en Valores Cívicos y Éticos"
    ],
    eso1: ['Biología y Geología', 'Educación Física', 'Educación Plástica, Visual y Audiovisual', 'Geografía e Historia', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Gallega y Literatura', 'Matemáticas', 'Segunda Lengua Extranjera', 'Tecnología y Digitalización'],
    eso2: ['Educación Física', 'Física y Química', 'Geografía e Historia', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Gallega y Literatura', 'Matemáticas', 'Música', 'Segunda Lengua Extranjera', 'Tecnología y Digitalización'],
    eso3: ['Biología y Geología', 'Cultura Clásica', 'Educación Digital', 'Educación Física', 'Educación Plástica, Visual y Audiovisual', 'Educación en Valores Cívicos y Éticos', 'Física y Química', 'Geografía e Historia', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Gallega y Literatura', 'Matemáticas', 'Música', 'Oratoria', 'Segunda Lengua Extranjera'],
    eso4: ['Biología y Geología', 'Cultura Clásica', 'Digitalización', 'Economía y Emprendimiento', 'Educación Física', 'Expresión Artística', 'Filosofía', 'Formación y Orientación Personal y Profesional', 'Física y Química', 'Geografía e Historia', 'Latín', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Gallega y Literatura', 'Matemáticas A', 'Matemáticas B', 'Música', 'Oratoria', 'Segunda Lengua Extranjera', 'Tecnología'],
    bach1: ['Anatomía Aplicada', 'Antropología', 'Análisis Musical', 'Artes Escénicas', 'Biología, Geología y Ciencias Ambientales', 'Coro y Técnica Vocal', 'Cultura Audiovisual', 'Cultura Científica', 'Dibujo Artístico', 'Dibujo Técnico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Economía', 'Economía, Emprendimiento y Actividad Empresarial', 'Educación Física', 'Filosofía', 'Física y Química', 'Griego', 'Historia del Mundo Contemporáneo', 'Latín', 'Latín ', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Gallega y Literatura', 'Lenguaje y Práctica Musical', 'Literatura Gallega del Siglo XX y de la Actualidad', 'Literatura Universal', 'Matemáticas', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Matemáticas Generales', 'Proyectos Artísticos', 'Segunda Lengua Extranjera', 'Tecnología e Ingeniería', 'Tecnologías de la Información y de la Comunicación', 'Volumen'],
    bach2: ['Análisis Musical', 'Artes Escénicas', 'Biología', 'Ciencias Generales', 'Coro y Técnica Vocal', 'Dibujo Artístico', 'Dibujo Técnico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Diseño', 'Empresa y Diseño de Modelos de Negocio', 'Fundamentos Artísticos', 'Física', 'Geografía', 'Geografía, Historia, Arte y Patrimonio de Galicia', 'Geología y Ciencias Ambientales', 'Griego', 'Historia de España', 'Historia de la Filosofía', 'Historia de la Música y de la Danza', 'Historia del Arte', 'Latín ', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Gallega y Literatura', 'Literatura Dramática', 'Matemática', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Movimientos Culturales y Artísticos', 'Métodos Estadísticos y Numéricos', 'Psicología', 'Química', 'Segunda Lengua Extranjera', 'Tecnología e Ingeniería', 'Tecnologías de la Información y de la Comunicación', 'Técnicas de Expresión Gráfico-Plástica']
}