const materiasGalicia = {
    eso1: [
        "Biología y Geología",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Segunda Lengua Extranjera",
        "Tecnología y Digitalización",
        "Geografía e Historia",
    ],
    eso2: [
        "Educación Física",
        "Física y Química",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología y Digitalización",
        "Geografía e Historia",
    ],
    eso3: [
        "Biología y Geología",
        "Educación en Valores Cívicos y Éticos",
        "Educación Física",
        "Educación Plástica, Visual y Audiovisual",
        "Física y Química",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas",
        "Música",
        "Geografía e Historia",
        "Cultura Clásica",
        "Educación Digital",
        "Oratoria",
        "Segunda Lengua Extranjera",
    ],
    eso4: [
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Lengua Gallega y Literatura",
        "Matemáticas A",
        "Matemáticas B",
        "Geografía e Historia",
        "Biología y Geología",
        "Digitalización",
        "Economía y Emprendimiento",
        "Expresión Artística",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Latín",
        "Música",
        "Segunda Lengua Extranjera",
        "Tecnología",
        "Cultura Clásica",
        "Filosofía",
        "Oratoria",
    ],
    bach1: ['Anatomía Aplicada', 'Antropología', 'Análisis Musical', 'Artes Escénicas', 'Biología, Geología y Ciencias Ambientales', 'Coro y Técnica Vocal', 'Cultura Audiovisual', 'Cultura Científica', 'Dibujo Artístico', 'Dibujo Técnico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Economía', 'Economía, Emprendimiento y Actividad Empresarial', 'Educación Física', 'Filosofía', 'Física y Química', 'Griego', 'Historia del Mundo Contemporáneo', 'Latín', 'Latín ', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Gallega y Literatura', 'Lenguaje y Práctica Musical', 'Literatura Gallega del Siglo XX y de la Actualidad', 'Literatura Universal', 'Matemáticas', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Matemáticas Generales', 'Proyectos Artísticos', 'Segunda Lengua Extranjera', 'Tecnología e Ingeniería', 'Tecnologías de la Información y de la Comunicación', 'Volumen'],
    bach2: ['Análisis Musical', 'Artes Escénicas', 'Biología', 'Ciencias Generales', 'Coro y Técnica Vocal', 'Dibujo Artístico', 'Dibujo Técnico', 'Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño', 'Diseño', 'Empresa y Diseño de Modelos de Negocio', 'Fundamentos Artísticos', 'Física', 'Geografía', 'Geografía, Historia, Arte y Patrimonio de Galicia', 'Geología y Ciencias Ambientales', 'Griego', 'Historia de España', 'Historia de la Filosofía', 'Historia de la Música y de la Danza', 'Historia del Arte', 'Latín ', 'Lengua Castellana y Literatura', 'Lengua Extranjera', 'Lengua Gallega y Literatura', 'Literatura Dramática', 'Matemática', 'Matemáticas Aplicadas a las Ciencias Sociales', 'Movimientos Culturales y Artísticos', 'Métodos Estadísticos y Numéricos', 'Psicología', 'Química', 'Segunda Lengua Extranjera', 'Tecnología e Ingeniería', 'Tecnologías de la Información y de la Comunicación', 'Técnicas de Expresión Gráfico-Plástica']
}