const materiasAndalucia = {
    ei: ['Todas las áreas'],
    ep1: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",

    ],
    ep2: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",
    ],
    ep3: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",
    ],
    ep4: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",
    ],
    ep5: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos",
    ],
    ep6: [
        "Conocimiento del Medio Natural, Social y Cultural",
        "Educación Artística",
        "Educación Física",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",
        "Educación en Valores Cívicos",
    ],
    eso1: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",
        "Biología y Geología",
        "Música",
        "Cultura Clásica",
        "Computación y Robótica",
        "Oratoria y Debate",

    ],
    eso2: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",
        "Física y Química",
        "Educación Plástica, Visual y Audiovisual",
        "Educación en Valores Cívicos y Éticos",
        "Tecnología y Digitalización",
        "Valores Cívicos y Éticos",
        "Cultura Clásica",
        "Computación y Robótica",
        "Música",
        "Oratoria y Debate",
    ],
    eso3: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas",
        "Biología y Geología",
        "Física y Química",
        "Educación Plástica, Visual y Audiovisual",
        "Tecnología y Digitalización",
        "Cultura Clásica",
        "Computación y Robótica",
        "Música",
        "Oratoria y Debate",
    ],
    eso4: [
        "Educación Física",
        "Geografía e Historia",
        "Lengua Castellana y Literatura",
        "Primera Lengua Extranjera",
        "Matemáticas A",
        "Matemáticas B",
        "Biología y Geología",
        "Digitalización",
        "Economía y Emprendimiento",
        "Expresión Artística",
        "Física y Química",
        "Formación y Orientación Personal y Profesional",
        "Latín",
        "Música",
        "Tecnología",
        "Artes escénicas y Danza",
        "Cultura Científica",
        "Ampliación de Cultura Clásica",
        "Filosofía",
        "Aprendizaje Social y Emocional",
    ],
    bach1: [
        "Educación Física",
        "Filosofía",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Dibujo Artístico",
        "Cultura Audiovisual",
        "Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño",
        "Proyectos Artísticos",
        "Volumen",
        "Análisis Musical",
        "Artes Escénicas",
        "Coro y Técnica Vocal",
        "Lenguaje y Práctica Musical",
        "Matemáticas",
        "Biología, Geología y Ciencias Ambientales",
        "Dibujo Técnico",
        "Física y Química",
        "Tecnología e Ingeniería",
        "Matemáticas Generales ",
        "Economía, Emprendimiento y Actividad Empresarial ",
        "Economía",
        "Griego",
        "Historia del Mundo Contemporáneo",
        "Latín",
        "Literatura Universal",
        "Matemáticas Aplicadas a las Ciencias Sociales",
    ],
    bach2: [
        "Historia de España",
        "Historia de la Filosofía",
        "Lengua Castellana y Literatura",
        "Lengua Extranjera",
        "Dibujo Artístico",
        "Dibujo Técnico Aplicado a las Artes Plásticas y al Diseño",
        "Diseño",
        "Fundamentos Artísticos",
        "Técnicas de Expresión Gráfico-plástica",
        "Análisis Musical",
        "Artes Escénicas",
        "Coro y Técnica Vocal",
        "Historia de la Música y de la Danza",
        "Literatura Dramática",
        "Matemáticas",
        "Matemáticas Aplicadas a las Ciencias Sociales",
        "Biología",
        "Dibujo Técnico",
        "Física",
        "Geología y Ciencias Ambientales",
        "Química",
        "Tecnología e Ingeniería",
        "Ciencias Generales ",
        "Movimientos Culturales y Artísticos ",
        "Latín",
        "Empresa y Diseño de Modelos de Negocio",
        "Geografía",
        "Griego",
        "Historia del Arte",
        
    ],
}